:sparkles: Add searchbar to emote picker
Daywalkerchen/awesome-extension pull request #49
Opened 2022-12-30 19:52 UTC by Daywalkerchen

2022-12-31 02:33 UTC, Daywalkerchen commented
🥺 May someone review me?

2022-12-31 10:10 UTC, Absebo requested changes

2022-12-31 10:10 UTC, Absebo commented on src/components/emote-picker/EmotePicker.jsx
> +  if (searchString) {
Looks like a bit of a code duplication here.

Both of your if-else-branches are mostly doing the same thing.
```
EMOTES
.filter((emote) => !searchString || emote.tags[0].toLowerCase().includes(searchString.toLowerCase())).`
.map(...)
```

2022-12-31 10:10 UTC, Absebo commented on src/components/emote-picker/EmotePicker.jsx
> +  console.log(searchString);
please remove `console.log`

2022-12-31 10:10 UTC, Absebo commented on src/components/search-bar/SearchBar.jsx
> +        placeholder="Suche"
> Suche

Should this really be a german word?

2023-01-18 16:25 UTC, cecob approved these changes
lgtm

2023-01-18 17:39 UTC, Absebo approved these changes

2023-01-18 17:57 UTC, merged